pipeline {
    agent any
    environment {
        DOCKER_HUB_ACCESS_TOKEN = credentials('ff9c84d8-539c-4fea-b4c5-ddf91cfa1108')
    }
    stages {
        stage('Build') {
            steps {
                sh 'docker-compose -f /Users/sarahkossmann/Desktop/Pycharm/Devops_projects/Final_project/docker-compose.yml build'
            }
        }
        stage('Run') {
            steps {
                sh 'docker-compose -f /Users/sarahkossmann/Desktop/Pycharm/Devops_projects/Final_project/docker-compose.yml up -d'
            }
        }
        stage('Test') {
            steps {
                sh 'python3 /Users/sarahkossmann/Desktop/Pycharm/Devops_projects/Final_project/Tests/e2e.py'
            }
        }
        stage('Login to Docker Hub') {
            steps {
                sh 'echo $DOCKER_HUB_ACCESS_TOKEN_PSW | docker login --username $DOCKER_HUB_ACCESS_TOKEN_USR --password-stdin'
            }
        }
        stage('Terminate container') {
            steps {
                sh 'docker-compose -f /Users/sarahkossmann/Desktop/Pycharm/Devops_projects/Final_project/docker-compose.yml stop'
            }
        }
        stage('Push image to Dockerhub') {
            steps {
                sh 'docker-compose -f /Users/sarahkossmann/Desktop/Pycharm/Devops_projects/Final_project/docker-compose.yml push'
            }
        }
    }
}